// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game.proto

package usercmd

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端发送的消息类型***
type MsgTypeCmd int32

const (
	MsgTypeCmd_None           MsgTypeCmd = 0
	MsgTypeCmd_Login          MsgTypeCmd = 1
	MsgTypeCmd_Top            MsgTypeCmd = 2
	MsgTypeCmd_AddPlayer      MsgTypeCmd = 3
	MsgTypeCmd_RemovePlayer   MsgTypeCmd = 4
	MsgTypeCmd_Scene          MsgTypeCmd = 5
	MsgTypeCmd_Move           MsgTypeCmd = 6
	MsgTypeCmd_PutBomb        MsgTypeCmd = 7
	MsgTypeCmd_Death          MsgTypeCmd = 10
	MsgTypeCmd_EndRoom        MsgTypeCmd = 11
	MsgTypeCmd_NewScene       MsgTypeCmd = 13
	MsgTypeCmd_ReSetNet       MsgTypeCmd = 15
	MsgTypeCmd_HeartBeat      MsgTypeCmd = 16
	MsgTypeCmd_SystemMsg      MsgTypeCmd = 22
	MsgTypeCmd_ErrorMsg       MsgTypeCmd = 23
	MsgTypeCmd_SceneSync      MsgTypeCmd = 100
	MsgTypeCmd_InitSyncData   MsgTypeCmd = 101
	MsgTypeCmd_AddPlayers     MsgTypeCmd = 102
	MsgTypeCmd_AddBalls       MsgTypeCmd = 104
	MsgTypeCmd_RemoveBalls    MsgTypeCmd = 105
	MsgTypeCmd_SetSceneData   MsgTypeCmd = 106
	MsgTypeCmd_CheckSyncData  MsgTypeCmd = 108
	MsgTypeCmd_SetPlayerAttrs MsgTypeCmd = 109
	MsgTypeCmd_UserStateSet   MsgTypeCmd = 111
	MsgTypeCmd_UserStateClr   MsgTypeCmd = 112
)

var MsgTypeCmd_name = map[int32]string{
	0:   "None",
	1:   "Login",
	2:   "Top",
	3:   "AddPlayer",
	4:   "RemovePlayer",
	5:   "Scene",
	6:   "Move",
	7:   "PutBomb",
	10:  "Death",
	11:  "EndRoom",
	13:  "NewScene",
	15:  "ReSetNet",
	16:  "HeartBeat",
	22:  "SystemMsg",
	23:  "ErrorMsg",
	100: "SceneSync",
	101: "InitSyncData",
	102: "AddPlayers",
	104: "AddBalls",
	105: "RemoveBalls",
	106: "SetSceneData",
	108: "CheckSyncData",
	109: "SetPlayerAttrs",
	111: "UserStateSet",
	112: "UserStateClr",
}

var MsgTypeCmd_value = map[string]int32{
	"None":           0,
	"Login":          1,
	"Top":            2,
	"AddPlayer":      3,
	"RemovePlayer":   4,
	"Scene":          5,
	"Move":           6,
	"PutBomb":        7,
	"Death":          10,
	"EndRoom":        11,
	"NewScene":       13,
	"ReSetNet":       15,
	"HeartBeat":      16,
	"SystemMsg":      22,
	"ErrorMsg":       23,
	"SceneSync":      100,
	"InitSyncData":   101,
	"AddPlayers":     102,
	"AddBalls":       104,
	"RemoveBalls":    105,
	"SetSceneData":   106,
	"CheckSyncData":  108,
	"SetPlayerAttrs": 109,
	"UserStateSet":   111,
	"UserStateClr":   112,
}

func (x MsgTypeCmd) Enum() *MsgTypeCmd {
	p := new(MsgTypeCmd)
	*p = x
	return p
}

func (x MsgTypeCmd) String() string {
	return proto.EnumName(MsgTypeCmd_name, int32(x))
}

func (x *MsgTypeCmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgTypeCmd_value, data, "MsgTypeCmd")
	if err != nil {
		return err
	}
	*x = MsgTypeCmd(value)
	return nil
}

func (MsgTypeCmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

type UserLoginInfo struct {
	Token                *string  `protobuf:"bytes,1,req,name=Token" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginInfo) Reset()         { *m = UserLoginInfo{} }
func (m *UserLoginInfo) String() string { return proto.CompactTextString(m) }
func (*UserLoginInfo) ProtoMessage()    {}
func (*UserLoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}
func (m *UserLoginInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserLoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserLoginInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserLoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginInfo.Merge(m, src)
}
func (m *UserLoginInfo) XXX_Size() int {
	return m.Size()
}
func (m *UserLoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginInfo proto.InternalMessageInfo

func (m *UserLoginInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("usercmd.MsgTypeCmd", MsgTypeCmd_name, MsgTypeCmd_value)
	proto.RegisterType((*UserLoginInfo)(nil), "usercmd.UserLoginInfo")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0xb4, 0x21, 0xcd, 0xa4, 0x6e, 0x87, 0x15, 0x02, 0x0e, 0xc8, 0x42, 0x48, 0x48,
	0x88, 0x43, 0x79, 0x00, 0x4e, 0x71, 0x5a, 0x89, 0x4a, 0x24, 0xaa, 0xec, 0x70, 0xe1, 0xb6, 0x78,
	0xa7, 0x4e, 0xa8, 0x77, 0xd7, 0xda, 0x9d, 0x16, 0xf9, 0x4d, 0x78, 0x24, 0x8e, 0x3c, 0x02, 0x0a,
	0x6f, 0xc1, 0x09, 0x8d, 0x5d, 0x45, 0xea, 0xf1, 0xff, 0x77, 0xfe, 0x6f, 0xf7, 0xdf, 0x01, 0xa8,
	0xb5, 0xa5, 0xf3, 0x36, 0x78, 0xf6, 0x6a, 0x72, 0x17, 0x29, 0x54, 0xd6, 0xbc, 0x79, 0x0b, 0xe9,
	0x97, 0x48, 0xe1, 0xb3, 0xaf, 0xb7, 0xee, 0xca, 0xdd, 0x78, 0xf5, 0x0c, 0xc6, 0x6b, 0x7f, 0x4b,
	0xee, 0x65, 0xf2, 0x7a, 0xf4, 0x6e, 0x5a, 0x0c, 0xe2, 0xfd, 0xbf, 0x11, 0xc0, 0x32, 0xd6, 0xeb,
	0xae, 0xa5, 0x85, 0x35, 0xea, 0x18, 0x8e, 0x56, 0xde, 0x11, 0x1e, 0xa8, 0x29, 0x8c, 0xfb, 0x2c,
	0x26, 0x6a, 0x02, 0x87, 0x6b, 0xdf, 0xe2, 0x48, 0xa5, 0x30, 0x9d, 0x1b, 0x73, 0xdd, 0xe8, 0x8e,
	0x02, 0x1e, 0x2a, 0x84, 0x93, 0x82, 0xac, 0xbf, 0xa7, 0x07, 0xe7, 0x48, 0x42, 0x65, 0x45, 0x8e,
	0x70, 0x2c, 0xa4, 0xa5, 0xbf, 0x27, 0x7c, 0xa2, 0x66, 0x30, 0xb9, 0xbe, 0xe3, 0xdc, 0xdb, 0x6f,
	0x38, 0x91, 0x89, 0x0b, 0xd2, 0xbc, 0x41, 0x10, 0xff, 0xd2, 0x99, 0xc2, 0x7b, 0x8b, 0x33, 0x75,
	0x02, 0xc7, 0x2b, 0xfa, 0x31, 0x84, 0x53, 0x51, 0x05, 0x95, 0xc4, 0x2b, 0x62, 0x3c, 0x93, 0x6b,
	0x3f, 0x91, 0x0e, 0x9c, 0x93, 0x66, 0x44, 0x91, 0x65, 0x17, 0x99, 0xec, 0x32, 0xd6, 0xf8, 0x5c,
	0x66, 0x2f, 0x43, 0xf0, 0x41, 0xd4, 0x8b, 0xfe, 0x50, 0x20, 0x65, 0xe7, 0x2a, 0x34, 0xf2, 0xc4,
	0x2b, 0xb7, 0x65, 0x51, 0x17, 0x9a, 0x35, 0x92, 0x3a, 0x05, 0xd8, 0x77, 0x88, 0x78, 0x23, 0xf1,
	0xb9, 0x31, 0xb9, 0x6e, 0x9a, 0x88, 0x1b, 0x75, 0x06, 0xb3, 0xa1, 0xd2, 0x60, 0x6c, 0x05, 0x50,
	0x12, 0xf7, 0xc8, 0x1e, 0xf0, 0x5d, 0x3d, 0x85, 0x74, 0xb1, 0xa1, 0xea, 0x76, 0xcf, 0x6c, 0x94,
	0x82, 0xd3, 0x92, 0x78, 0x60, 0xce, 0x99, 0x43, 0x44, 0x2b, 0x41, 0xf9, 0xff, 0x92, 0x35, 0x4b,
	0x13, 0xf4, 0x8f, 0x9c, 0x45, 0x13, 0xb0, 0xcd, 0x5f, 0xfd, 0xda, 0x65, 0xc9, 0xef, 0x5d, 0x96,
	0xfc, 0xd9, 0x65, 0xc9, 0xcf, 0xbf, 0xd9, 0xc1, 0x57, 0x38, 0xff, 0xf0, 0xf1, 0x61, 0x83, 0xff,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xee, 0x9b, 0x54, 0xc7, 0xd7, 0x01, 0x00, 0x00,
}

func (m *UserLoginInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserLoginInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserLoginInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Token == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.Token)
		copy(dAtA[i:], *m.Token)
		i = encodeVarintGame(dAtA, i, uint64(len(*m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGame(dAtA []byte, offset int, v uint64) int {
	offset -= sovGame(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserLoginInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Token != nil {
		l = len(*m.Token)
		n += 1 + l + sovGame(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovGame(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGame(x uint64) (n int) {
	return sovGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserLoginInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserLoginInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserLoginInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Token = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGame
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGame
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGame        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGame = fmt.Errorf("proto: unexpected end of group")
)
